# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-14 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200314_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Children', 'Children'), ('Accessories', 'Accessories')], max_length=50),
        ),
    ]
