# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ManyToManyField(related_name='product_colors', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ManyToManyField(related_name='product_sizes', to='shop.Product'),
        ),
    ]
