# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-19 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200319_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name': 'Product Option', 'verbose_name_plural': 'Product Options'},
        ),
        migrations.AlterField(
            model_name='options',
            name='color',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='options',
            name='size',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
